Make docroot and server name configurable.
drupal-docker/nginx pull request #13
Opened 2016-10-15 18:40 UTC by slashrsm

Based on discussion in https://github.com/drupal-docker/php/issues/46.

Fixes #6.

2016-10-16 20:28 UTC, zaporylie requested changes
I like sed-based approach. Have some doubts though about naming convention and entrypoint usage. Added some inline comments to place it in the context.

Just created pull request to your fork-branch with my suggestions. Curious to hear your opinion :)

Thank you for your involvement and pushing this long-standing issue forward.

2016-10-16 20:28 UTC, zaporylie commented on mainline-alpine/Dockerfile
> +CMD "entrypoint.sh"
Should use ENTRYPOINT instruction

2016-10-16 20:28 UTC, zaporylie commented on mainline-alpine/drupal.conf
> +    server_name SERVER_NAME;
Why do we need it?

2016-10-16 20:28 UTC, zaporylie commented on mainline-alpine/drupal.conf
>      root /var/www/html;
IMHO we should tokenize `root` as well. I suggest name nginx independent so I could implement it the same way in drupal-docker/apache (maybe `DOCROOT`).

```
root DOCROOT
```

Probably even better to use before/after special char, something like `%SERVER_NAME%` and `%DOCROOT%`

2016-10-16 20:28 UTC, zaporylie commented on mainline-alpine/entrypoint.sh
> +if [ -n "$NGINX_DOCROOT" ]; then
As I have mentioned before, this variable should be nginx independent. Maybe just `DOCROOT`?

2016-10-16 20:28 UTC, zaporylie commented on mainline-alpine/entrypoint.sh
> +exec nginx -g "daemon off;"
This script is suppose to be `ENTRYPOINT` so it should accept command argument and execute it. See https://github.com/docker-library/mysql/blob/master/5.5/docker-entrypoint.sh#L151 or https://github.com/docker-library/redis/blob/master/3.0/docker-entrypoint.sh#L16

2016-10-16 20:28 UTC, zaporylie commented on mainline-alpine/Dockerfile
> +
Environment variables should be declared in Dockerfile.

2016-10-17 07:42 UTC, slashrsm commented
Makes sense. It your PR you didn't use replacement tokens with special characters as you mentioned in one of the comments. Should we do that?

Thank you for helping. I am constantly learning when contributing to this project.

2016-10-17 08:07 UTC, zaporylie commented
Yes, I think we should. As we use `sed` to change *all* the config files containing SERVER_NAME or DOCROOT (not just default.conf) we should make sure we replace only tokens which suppose to be replaced, not all occurrences of SERVER_NAME and DOCROOT string.

Still not sure why you suggested changing default server_name from `_` to `drupal`? Probably both would work by default but IMHO `_` should be used for catch-all server as it is quite common practice (ref. http://nginx.org/en/docs/http/server_names.html).

2016-10-17 08:21 UTC, slashrsm commented
> Yes, I think we should. As we use sed to change all the config files containing SERVER_NAME or DOCROOT (not just default.conf) we should make sure we replace only tokens which suppose to be replaced, not all occurrences of SERVER_NAME and DOCROOT string.

Done

> Still not sure why you suggested changing default server_name from _ to drupal? Probably both would work by default but IMHO _ should be used for catch-all server as it is quite common practice (ref. http://nginx.org/en/docs/http/server_names.html).

Not really sure about that. Reverted back to "_" while still offering to override it.

2016-10-17 08:31 UTC, zaporylie approved these changes

2016-10-17 19:33 UTC, merged